import type { ApplicationCommandData } from 'discord.js';

export const SLASH_COMMANDS: ApplicationCommandData[] = [
  { name: 'help',              type: 1, description: 'Show available commands' },
  { name: 'start',             type: 1, description: 'Start streaming local video queue' },
  {
    name: 'play',
    type: 1,
    description: 'Play a YouTube URL',
    options: [{ name: 'url', type: 3, description: 'YouTube URL', required: true }],
  },
  {
    name: 'audio',
    type: 1,
    description: 'Play audio from a URL',
    options: [{ name: 'url', type: 3, description: 'Audio URL', required: true }],
  },
  {
    name: 'search',
    type: 1,
    description: 'Search YouTube and play top result',
    options: [{ name: 'query', type: 3, description: 'Search query', required: true }],
  },
  {
    name: 'search-pick',
    type: 1,
    description: 'Search YouTube and pick from top 5',
    options: [{ name: 'query', type: 3, description: 'Search query', required: true }],
  },
  {
    name: 'search-channel',
    type: 1,
    description: "Browse a YouTube channel's videos",
    options: [{ name: 'name', type: 3, description: 'Channel name', required: true }],
  },
  {
    name: 'music-search',
    type: 1,
    description: 'Search and play as audio',
    options: [{ name: 'query', type: 3, description: 'Search query', required: true }],
  },
  {
    name: 'music-search-pick',
    type: 1,
    description: 'Search and pick from top 5 as audio',
    options: [{ name: 'query', type: 3, description: 'Search query', required: true }],
  },
  {
    name: 'pick',
    type: 1,
    description: 'Pick from pending search results',
    options: [{ name: 'number', type: 4, description: 'Result number', required: true }],
  },
  { name: 'pause',             type: 1, description: 'Pause the stream' },
  { name: 'resume',            type: 1, description: 'Resume the stream' },
  { name: 'stop',              type: 1, description: 'Stop and leave voice' },
  { name: 'skip',              type: 1, description: 'Skip to next in queue' },
  { name: 'loop',              type: 1, description: 'Toggle loop current track' },
  { name: 'loopqueue',         type: 1, description: 'Toggle loop entire queue' },
  { name: 'queue',             type: 1, description: 'Show video queue' },
  {
    name: 'queue-add',
    type: 1,
    description: 'Add a YouTube URL to the video queue',
    options: [{ name: 'url', type: 3, description: 'YouTube URL', required: true }],
  },
  { name: 'queue-play',        type: 1, description: 'Play from video queue' },
  { name: 'queue-clear',       type: 1, description: 'Clear the video queue' },
  { name: 'audio-mode',        type: 1, description: 'Toggle audio-only mode' },
  { name: 'aq',                type: 1, description: 'Show audio queue' },
  {
    name: 'aq-remove',
    type: 1,
    description: 'Remove item from audio queue',
    options: [{ name: 'number', type: 4, description: 'Item number', required: true }],
  },
  { name: 'aq-clear',          type: 1, description: 'Clear the audio queue' },
  { name: 'loop-audio',        type: 1, description: 'Toggle loop current audio track' },
  { name: 'loop-audio-queue',  type: 1, description: 'Toggle loop entire audio queue' },
];
